#!/bin/sh

set -e
# set -x 

# 拉取远程分支
fetchAll(){
  git fetch --all
}

# 获取当前分支名
getCurrentBranch(){
  branch=$(git rev-parse --abbrev-ref HEAD)
  echo "$branch";
}

# 重制分支
resetHard(){
  currentBranch=$(getCurrentBranch)
  git reset --hard "origin/$currentBranch";
  if [ -n "$1" ] && [ "$currentBranch" != "$1" ]; then
      git checkout "$1";
      if [ $? -eq 1 ]; then
          return;
      fi
  fi
}

# 重制到最新的分支版本
resetToLast(){
  fetchAll;
  deleteChangeFiles;
  resetHard "$1";
  git pull
  git diff;
  git status;
}

# 获取未添加到git分支的文件
getChangeFiles(){
  git status --porcelain 2>/dev/null | awk '{print $2}'
}

# 删除未添加到git分支的所有文件
deleteChangeFiles(){
  getChangeFiles | xargs -n1 rm -rf
}

help() {
  printf "resetToLast [branchName]\n"
  printf "getChangeFiles\n"
  printf "cleanFiles\n"
}

main(){
  case $1 in
    'resetToLast')
      resetToLast "$2"
	  ;;
	  'getChangeFiles')
	    getChangeFiles
	  ;;
	  'cleanFiles')
	    deleteChangeFiles
	  ;;
    '-h' | '--help')
      help
      ;;
    *)
      printf 'no options!!\n'
      help
    ;;
  esac
}

main "$@";

